# local makefile, where the sources are.
# here the makefile for (top)/FR/dyade/koala/graphics/editor

# remember to adjust the following variables.

# where the root dir is
TOP_DIR		=../../../../../..
#where the classes are put under the class dir (required for "make clean")
PACKAGE_DIR	=no/hiof/mobapp/foxhunt/gamebehavior

include $(TOP_DIR)/Makefile.include

