print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/ann-charlottkarlsen/Desktop/Fox/Client/Assets/Prefab/Fox2.mb"`)
{		
	file -o "/Users/ann-charlottkarlsen/Desktop/Fox/Client/Assets/Prefab/Fox2.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/ann-charlottkarlsen/Desktop/Fox/Client/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/ann-charlottkarlsen/Desktop/Fox/Client/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/ann-charlottkarlsen/Desktop/Fox/Client/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
